name: "Notify PR Open in Slack and Add Reaction on Merge"

inputs:
  CHANNEL_ID:
    description: "Channel ID"
  BOT_TOKEN_GITHUB:
    description: "Slack bot token"
  TEAM_NAME:
    description: "Slack team name"

runs:
  using: "composite"
  steps:
    - name: Notify to Slack channel
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
      uses: slackapi/slack-github-action@v1.23.0
      id: notify_slack
      with:
        channel-id: ${{ inputs.CHANNEL_ID }}
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:pr_open: Review required @${{ inputs.TEAM_NAME }} by ${{ github.event.pull_request.user.login }}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*${{ github.event.pull_request.title }}*"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Review here",
                    "emoji": true
                  },
                  "value": "review_here",
                  "url": "${{ github.event.pull_request.html_url }}",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.BOT_TOKEN_GITHUB }}

    - name: Add reaction to Slack message
      if: github.event.action == 'closed' && github.event.pull_request.merged == true && steps.get_slack_messages.outputs.result != '[]'
      uses: slack/web-api@v1
      with:
        slack-bot-token: ${{ inputs.BOT_TOKEN_GITHUB }}
        method: conversations.history
        channel: ${{ inputs.CHANNEL_ID }}
        limit: 100
      id: get_slack_messages
    - name: Find original message
      if: github.event.action == 'closed' && github.event.pull_request.merged == true && steps.get_slack_messages.outputs.result != '[]'
      id: find_message
      run: |
        for message in ${{ fromJson(steps.get_slack_messages.outputs.result).messages }}; do
          if [[ "$message" == *"${{ github.event.pull_request.title }}"* ]]; then
            echo "::set-output name=ts::$(echo $message | jq -r '.ts')"
            break
          fi
        done
      if: steps.get_slack_messages.outputs.result != '[]'
    - name: Add reaction to Slack message
      if: github.event.action == 'closed' && github.event.pull_request.merged == true && steps.get_slack_messages.outputs.result != '[]'
      uses: slack/web-api@v1
      with:
        slack-bot-token: ${{ inputs.BOT_TOKEN_GITHUB }}
        method: reactions.add
        name: merged
        channel: ${{ inputs.CHANNEL_ID }}
        timestamp: ${{ steps.find_message.outputs.ts }}
      if: steps.get_slack_messages.outputs.result != '[]'
