name: "Notify PR Open in Slack"
inputs:
  CHANNEL_ID: 
    description: "Channel ID"
  BOT_TOKEN_GITHUB:
    description: "Slack bot token"
  TEAM_NAME:
    description: "Slack bot token"
  
runs:
  using: "composite"
  steps:
    - name: Notify to Slack channel
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.CHANNEL_ID}}
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:pr_open: Review required @${{ inputs.TEAM_NAME}} by ${{ github.event.pull_request.user.login }}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*${{ github.event.pull_request.title }}*"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Review here",
                    "emoji": true
                  },
                  "value": "review_here",
                  "url": "${{ github.event.pull_request.html_url }}",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.BOT_TOKEN_GITHUB}}

    - name: Notify to Slack channel
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.CHANNEL_ID}}
        update-ts: ${{ steps.slack.outputs.ts }}
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*:merged: Pull request has been merged @${{ inputs.TEAM_NAME}} by ${{ github.event.pull_request.user.login }}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*${{ github.event.pull_request.title }}*"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Check here",
                    "emoji": true
                  },
                  "value": "review_here",
                  "url": "${{ github.event.pull_request.html_url }}",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.BOT_TOKEN_GITHUB}}
